# CoolerControl Service Plugin Manifest

id = "custom-device"

type = "device"

version = "0.1.0"

url = "https://gitlab.com/coolercontrol/cc-plugin-custom-device"

description = "A custom device service where users can use shell commands to monitor and control their devices."

address = "/tmp/custom-device.sock"

executable = "custom-device"

privileged = true
